// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9BIIJtnz4mzuKKyJo8-ybzXVfxe_8tBc',
    appId: '1:465685358722:web:29952b3afefe9c228fec9b',
    messagingSenderId: '465685358722',
    projectId: 'inventory-management-1aa57',
    authDomain: 'inventory-management-1aa57.firebaseapp.com',
    storageBucket: 'inventory-management-1aa57.appspot.com',
    measurementId: 'G-JJC7V02BN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6UsV9oZp1NLo0-UbCBwU7aWXCYbWjD3A',
    appId: '1:465685358722:android:fd398c39d68de65d8fec9b',
    messagingSenderId: '465685358722',
    projectId: 'inventory-management-1aa57',
    storageBucket: 'inventory-management-1aa57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhZVO5GMFBbWvf-LqL9FmpsEk7B9Ah8qI',
    appId: '1:465685358722:ios:070c1a7f5a5c95cc8fec9b',
    messagingSenderId: '465685358722',
    projectId: 'inventory-management-1aa57',
    storageBucket: 'inventory-management-1aa57.appspot.com',
    iosBundleId: 'com.example.richCoInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhZVO5GMFBbWvf-LqL9FmpsEk7B9Ah8qI',
    appId: '1:465685358722:ios:bf5f760026031b4d8fec9b',
    messagingSenderId: '465685358722',
    projectId: 'inventory-management-1aa57',
    storageBucket: 'inventory-management-1aa57.appspot.com',
    iosBundleId: 'com.example.richCoInventory.RunnerTests',
  );
}
